services:
  la-pinecone:
    image: ghcr.io/pinecone-io/pinecone-local:latest
    container_name: la-pinecone-service
    restart: unless-stopped
    ports:
      - "5080:5080"
      - "5081:5081"
    networks:
      - backend-net

  la-milvus:
    image: milvusdb/milvus:v2.3.5
    container_name: la-milvus-service
    command: milvus run standalone
    ports:
      - "19530:19530"
    environment:
      ETCD_USE_EMBED: "true"
      COMMON_STORAGETYPE: local
    networks:
      - backend-net
    volumes:
      - ./backend/vector_database_tests/utils/data_storage/milvus_data:/var/lib/milvus

  la-qdrant:
    image: qdrant/qdrant:v1.16.1
    restart: unless-stopped
    container_name: la-qdrant-service
    ports:
      - "6333:6333"
    networks:
      - backend-net
    volumes:
      - ./backend/vector_database_tests/utils/data_storage/qdrant_data:/qdrant/storage

  la-weaviate:
    image: semitechnologies/weaviate:1.34.8
    container_name: la-weaviate-service
    restart: unless-stopped
    ports:
      - "8083:8080"
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      ENABLE_MODULES: ""
      DEFAULT_VECTORIZER_MODULE: ""
      CLUSTER_HOSTNAME: "node1"
    networks:
      - backend-net
    volumes:
      - ./backend/vector_database_tests/utils/data_storage/weaviate_data:/var/lib/weaviate

#   la-elasticsearch:
#     image: docker.elastic.co/elasticsearch/elasticsearch:8.17.10
#     restart: unless-stopped
#     container_name: la-eslaticsearch-service
#     ports:
#       - "9200:9200"
#     networks:
#       - backend-net
#     environment:
#       - discovery.type=single-node
#       - xpack.security.enabled=false
#       - ES_JAVA_OPTS=-Xms256m -Xmx256m
#     volumes:
#       - ./backend/vector_database_tests/utils/data_storage/elasticsearch_data:/usr/share/elasticsearch/data

  la-mongodb:
    image: mongo:8.0.13-noble
    restart: unless-stopped
    container_name: la-mongodb-service
    ports:
      - "8006:27017"
    networks:
      - backend-net
    volumes:
      - ./backend/vector_database_tests/utils/data_storage/mongodb_data:/data/db

  la-redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    container_name: la-redis-service
    ports:
      - "8007:6379"
    networks:
      - backend-net
    volumes:
      - ./backend/vector_database_tests/utils/data_storage/redis_data:/data

  la-vespa:
    image: vespaengine/vespa:8.629.20
    restart: unless-stopped
    container_name: la-vespa-service
    hostname: vespa-container
    ports:
      - "8080:8080"
      - "19071:19071"
    networks:
      - backend-net
    volumes:
      - ./backend/vector_database_tests/utils/vespa_config:/app
      - ./backend/vector_database_tests/utils/data_storage/vespa_data:/opt/vespa/var
    deploy:
      resources:
        limits:
          memory: 4g

  la-backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file:
      - .env
    depends_on:
      - la-vespa
      - la-qdrant
      - la-milvus
      - la-pinecone
      - la-weaviate
      - la-mongodb
      - la-redis
    stdin_open: true
    tty: true
    restart: always
    container_name: la-backend-service
    ports:
      - "2010:2010"
    networks:
      - backend-net
    volumes:
      - ./backend:/backend

networks:
  backend-net:
    driver: bridge