tag = {
    "criminal_law_tags": [
        "criminal_law", "crime", "felony", "misdemeanor", "infraction", "arrest", "bail", "bond", "trial", "jury",
        "indictment", "arraignment", "plea", "plea_bargain", "conviction", "sentence", "acquittal", "parole", "probation",
        "prosecution", "defense", "defendant", "plaintiff", "witness", "evidence", "testimony", "cross_examination",
        "direct_examination", "burden_of_proof", "reasonable_doubt", "guilt", "innocence", "mens_rea", "actus_reus",
        "intent", "premeditation", "recklessness", "negligence", "attempt", "conspiracy", "accomplice", "aiding_abetting",
        "accessory", "homicide", "murder", "manslaughter", "assault", "battery", "kidnapping", "rape", "sexual_assault",
        "domestic_violence", "stalking", "harassment", "theft", "larceny", "burglary", "robbery", "extortion",
        "embezzlement", "fraud", "money_laundering", "bribery", "corruption", "arson", "vandalism", "trespassing",
        "cybercrime", "computer_fraud", "identity_theft", "hacking", "phishing", "drug_crime", "possession", "distribution",
        "trafficking", "DUI", "DWI", "public_intoxication", "disorderly_conduct", "resisting_arrest", "obstruction",
        "perjury", "contempt_of_court", "escape", "fugitive", "bench_warrant", "search_warrant", "probable_cause",
        "Miranda_rights", "interrogation", "confession", "self_incrimination", "double_jeopardy", "due_process",
        "cruel_and_unusual", "death_penalty", "capital_punishment", "life_sentence", "minimum_sentence", "maximum_sentence",
        "statute_of_limitations", "juvenile_crime", "youth_offender", "gang_activity", "organized_crime",
        "racketeering", "RICO", "terrorism", "hate_crime", "bias_motivated_crime", "civil_rights_violation",
        "entrapment", "alibi", "insanity_defense", "competency", "plea_insanity", "self_defense", "stand_your_ground",
        "castle_doctrine", "necessity_defense", "duress", "mistake_of_fact", "mistake_of_law", "intoxication_defense",
        "statutory_rape", "child_abuse", "elder_abuse", "abduction", "witness_tampering", "jury_tampering",
        "judicial_misconduct", "prosecutorial_misconduct", "ineffective_counsel", "appeal", "habeas_corpus",
        "postconviction_relief", "expungement", "pardon", "clemency", "commutation", "restitution", "rehabilitation",
        "recidivism", "three_strikes_law", "mandatory_minimum", "sentencing_guidelines", "parole_board",
        "community_service", "house_arrest", "electronic_monitoring", "probation_violation", "supervised_release",
        "court_martial", "military_crime", "martial_law", "international_criminal_law", "war_crime", "genocide",
        "crime_against_humanity", "Interpol", "extradition", "jurisdiction", "venue", "criminal_code", "penal_code",
        "model_penal_code", "federal_crime", "state_crime", "miscarriage_of_justice", "wrongful_conviction",
        "exoneration", "DNA_evidence", "forensic_evidence", "ballistics", "fingerprint", "crime_scene", "surveillance",
        "lineup", "mugshot", "booking", "charge", "arraignment_hearing", "pretrial_motions", "suppression_motion",
        "discovery", "jury_selection", "voir_dire", "opening_statement", "closing_argument", "verdict", "sentencing_phase",
        "mitigating_factors", "aggravating_factors", "appeals_court", "supreme_court", "pro_se_defendant",
        "public_defender", "private_attorney", "district_attorney", "special_prosecutor", "grand_jury",
        "preliminary_hearing", "no_contest", "nolo_contendere", "hung_jury", "mistrial", "retrial", "plea_agreement",
        "restorative_justice", "victim_impact", "criminal_record", "background_check", "incarceration", "jail", "prison"
    ],
}